theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
ssid = true
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "cw2015-battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
